### ISSUE TITLE
Error loading library

### ISSUE THREAD

**Issue by EduardoDiNizo** [ertwroc/opensc-java#1]
I'm trying to load the PKCS11Provider class but this error is showing up. Do you have any idea what it might be? 
--------------------------------------------------------------------
Source:
public static void main(String[] args) {
        PKCS11Provider provider;
        String pkcs11_path = "/usr/lib/opensc-pkcs11.so";

        try {
            provider = new PKCS11Provider(pkcs11_path);
        } catch (IOException e) {
            e.printStackTrace();
        }
}
-------------------------------------------------------------------
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opensc-PKCS11-0.3 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.opensc.pkcs11.PKCS11Provider.<clinit>(PKCS11Provider.java:70)
	at org.opensc.Main.main(Main.java:18)

**Comment by ertwroc** [comment]
[In this line](https://github.com/ertwroc/opensc-java/blob/86c57eec5084e4e7dd93934d7e644d2ef1480be5/pkcs11/java/src/org/opensc/pkcs11/PKCS11Provider.java#L70) you load library which does not exist in your system. So you are missing shared library in your system or you have to update version attribute.

Please also notice that this code is not maintained and this is not official source code of opensc.

**Comment by EduardoDiNizo** [comment]
Ok. Thanks!
